default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', '') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', '3306') %>

development:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE', 'performance_challenge_development') %>

test:
  <<: *default
  database: performance_challenge_test

production:
  <<: *default
  database: performance_challenge_production